### PR TITLE
Issue #76 Search Bar

### PR DESCRIPTION
**Pull request by danielochka**
I have created Search Bar in Webinar Page and added some css features in style1.css

### CODE REVIEW

**Comment by akanksha-raghav** [comment]
Hey @danielochka I have reviewed your code here you need to do some changes:
- When anyone searches it should not redirect to the youtube page it should remain on the same page and give a result.
- Add keyword feature like if there is a webinar named "Cloud platform" then if someone types "cloud" it should come on the top. You can refer to https://scodein.tech/project.html the search bar provided here. 
Make changes and make a pull request to the studentcode-in repo instead of creating an issue in your own repo.
For creating a pull request refer here: https://opensource.com/article/19/7/create-pull-request-github
If you have any issues feel free to ask.

**Comment by danielochka** [comment]
Thank you very much, I'll try my best.

Dňa ut 27. 10. 2020, 8:21 Akanksha Raghav <notifications@github.com>
napísal(a):

**Comment by danielochka** [comment]
@akanksha-raghav I think I pulled request into my repo again. I'm using WebStorm and I have comitted it from WebStorm and then clicked here on this page on pull request. Please check the functionality. I think it's working.

**Comment by akanksha-raghav** [comment]
There is no pull request with the changes kindly push it to Master branch

**Comment by danielochka** [comment]
Did you get pull request now?

**Pull request merged**
